
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"
[[mods]] #mandatory
modId="elysia" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Elysia's Mod" #mandatory

logoFile="examplemod.png" #optional
credits="Thanks for this mod Elysia goes to Java"
authors="Love, Cheese and small house plants"
description='''
This is a long form description of the mod. You can write whatever you want here

very cool 
'''
[[dependencies.elysia]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
